casillerosapp/urls.py
from django.urls import path 
from casillerosapp.views import views
from casillerosapp.views.mqtt import mqtt_views
from casillerosapp.views.controladores import controladores_view

urlpatterns = [
    path("", views.home, name='home'),
    path("login/", views.login, name="login"),  
    path("logout/", views.logout, name='logout'),
    path('mqtt/', mqtt_views.mqtt_view, name='mqtt'),
    path('mqtt/messages/', mqtt_views.show_messages_view, name='show_messages_view'),
    path('lista_controladores', controladores_view.lista_controladores, name='lista_controladores'),
    path('<int:controlador_id>/', controladores_view.detalle_controlador, name='detalle_controlador'),
    path('actualizar_casillero_usuario/<int:casillero_id>/', controladores_view.actualizar_casillero_usuario, name='actualizar_casillero_usuario'),
    path('cargar_formulario_usuario/<int:casillero_id>/', controladores_view.cargar_formulario_usuario, name='cargar_formulario_usuario'),
    path('obtener_logs/<int:casillero_id>/', controladores_view.obtener_logs, name='obtener_logs'),
    path("get_logs_statistics/", views.get_logs_statistics, name="get_logs_statistics"),
]

casillerosproject/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")), 
    path("", include('casillerosapp.urls'))
]

casillerosapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from datetime import timedelta

class User(AbstractUser):
    ROLE_CHOICES = (
        ('Superuser', 'Superuser'),
        ('User', 'User'),
    )
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='User')
    total_time_used = models.DurationField(default=timedelta())  # Tiempo total acumulado
    last_login_time = models.DateTimeField(null=True, blank=True)  # Último inicio de sesión

    # Ajustar los related_name para evitar conflictos
    groups = models.ManyToManyField(
        Group,
        related_name="user_group",  # Cambia el related_name para evitar conflictos
        blank=True,
        help_text="The groups this user belongs to.",
        verbose_name="groups",
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name="role_permisions",  # Cambia el related_name para evitar conflictos
        blank=True,
        help_text="Specific permissions for this user.",
        verbose_name="user permissions",
    )


class Controlador(models.Model):
    nombre = models.CharField(max_length=100, unique=True, help_text="Nombre del controlador")
    ultima_conexion = models.DateTimeField(auto_now=True, help_text="Última conexión con el controlador")

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Controlador"
        verbose_name_plural = "Controladores"

class Casillero(models.Model):
    identificador = models.CharField(max_length=50, unique=True, help_text="Identificador único del casillero")
    email = models.EmailField(max_length=50, blank=True)
    controlador = models.ForeignKey(Controlador, on_delete=models.CASCADE, related_name="casilleros")
    ubicacion = models.CharField(max_length=100, blank=True, help_text="Ubicación física del casillero")
    abierto = models.BooleanField(default=False)
    clave = models.CharField(default="0000")
    _skip_signal = False

    def __str__(self):
        return f"{self.identificador} - {self.controlador.nombre}"

    class Meta:
        verbose_name = "Casillero"
        verbose_name_plural = "Casilleros"

class Logs(models.Model):
    TYPE_CHOICES = (
        ('Cambio_contraseña', 'Cambio de contraseña'),
        ('Apertura', 'Apertura de casillero'),
        ('Cierre', 'Cierre de casillero'),
        ('Error', 'Error de Apertura'),
    )
    type = models.CharField(max_length=100, choices=TYPE_CHOICES)
    casillero = models.ForeignKey(Casillero, on_delete=models.CASCADE, related_name="logs")
    fecha = models.DateTimeField()
    mensaje = models.TextField()
    password= models.CharField(max_length=5, blank=True)

casillerosapp/forms.py
from django import forms
from .models import Casillero
from casillerosapp.choices import KEY_CHOICES

class UsuarioCasilleroForm(forms.Form):
    usuario_email = forms.EmailField(
        required=False,
        label="Email Dueño",
        widget=forms.EmailInput(attrs={
            'placeholder': 'Ingrese email dueño',
            'style': 'width: 65%;'
        })
    )
    
    # Campos de la clave con clase 'form-select' para Select2
    clave1 = forms.ChoiceField(
        choices= KEY_CHOICES,
        label="Clave 1",
        required=True,
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    clave2 = forms.ChoiceField(
        choices=KEY_CHOICES,
        label="Clave 2",
        required=True,
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    clave3 = forms.ChoiceField(
        choices=KEY_CHOICES,
        label="Clave 3",
        required=True,
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    clave4 = forms.ChoiceField(
        choices=KEY_CHOICES,
        label="Clave 4",
        required=True,
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    def __init__(self, *args, casillero=None, **kwargs):
        super().__init__(*args, **kwargs)
        if casillero and casillero.email:
            self.fields['usuario_email'].widget.attrs['placeholder'] = casillero.email
            # Si hay una clave ya existente, predefinirla en los selectores
            if casillero.clave:
                clave = casillero.clave
                self.fields['clave1'].initial = clave[0]
                self.fields['clave2'].initial = clave[1]
                self.fields['clave3'].initial = clave[2]
                self.fields['clave4'].initial = clave[3]

casillerosapp/views/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as django_logout
from django.contrib.auth.decorators import login_required
from casillerosapp.models import Casillero, Logs
from django.db.models import Count
from datetime import timedelta
from django.utils.timezone import now
from django.http import JsonResponse
from django.db.models import Q, F
from django.core.paginator import Paginator
from casillerosapp.models import User


def login(request): 
    if request.user.is_authenticated:
        return redirect("/")
    return render(request, "base/login.html")

def logout(request):
    # Cierra la sesión del usuario
    django_logout(request)
    print("Logout realizado correctamente")
    return redirect("login")

@login_required(login_url='/login')
def home(request):
    user = request.user

    # Información básica del usuario
    name = user.first_name.capitalize() if user.first_name else ''
    last_name = user.last_name.capitalize() if user.last_name else ''

    # Calcula el tiempo desde el último inicio de sesión
    if user.last_login_time:
        elapsed_time = now() - user.last_login_time
        user.total_time_used += elapsed_time
        user.last_login_time = now()
        user.save()

    # Formatear el tiempo total de uso en formato HH:MM:SS
    total_seconds = int(user.total_time_used.total_seconds())
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    total_time_formatted = f"{hours:02}:{minutes:02}:{seconds:02}"

    if user.role == "Superuser":
        # Obtener usuarios con el rol "User"
        usuarios = User.objects.filter(role="User")

        # Determinar el rango de días para las estadísticas (por defecto 7 días)
        days = int(request.GET.get('days', 7))
        start_date = now() - timedelta(days=days)

        # Preparar estadísticas de usuarios
        usuarios_data = []
        for usuario in usuarios:
            casillero_count = Casillero.objects.filter(email=usuario.email).count()
            casillero_ids = Casillero.objects.filter(email=usuario.email).values_list('id', flat=True)
            interactions = Logs.objects.filter(casillero_id__in=casillero_ids, fecha__gte=start_date).count()

            # Formatear tiempo de uso
            total_seconds = int(usuario.total_time_used.total_seconds())
            hours, remainder = divmod(total_seconds, 3600)
            minutes, seconds = divmod(remainder, 60)
            total_time_formatted_user = f"{hours:02}:{minutes:02}:{seconds:02}"

            usuarios_data.append({
                'first_name': usuario.first_name.split()[0].capitalize(),
                'last_name': usuario.last_name.split()[0].capitalize(),
                'casillero_count': casillero_count,
                'total_time_formatted': total_time_formatted_user,
                'interactions': interactions,
            })

        # Paginación
        paginator = Paginator(usuarios_data, 5)  # 10 usuarios por página
        page_number = request.GET.get('page', 1)
        usuarios_page = paginator.get_page(page_number)

        # Datos para el gráfico de radar
        casillero_logs = Logs.objects.filter(fecha__gte=start_date).values('casillero__identificador').annotate(
            total_interactions=Count('id')
        )
        radar_labels = [log['casillero__identificador'] for log in casillero_logs]
        radar_data = [log['total_interactions'] for log in casillero_logs]

        context = {
            'name': name,
            'last_name': last_name,
            'role': user.role,
            'usuarios': usuarios_page,  # Datos paginados
            'radar_labels': radar_labels,
            'radar_data': radar_data,
            'days': days,
        }
    else:
        # Dashboard del usuario
        casilleros = Casillero.objects.filter(email=user.email)

        # Tipos de logs esperados
        TIPOS_LOGS = ["Apertura", "Cierre", "Cambio_contraseña"]

        # Por defecto, mostrar estadísticas de los últimos 7 días
        start_date = now() - timedelta(days=7)
        log_stats = Logs.objects.filter(casillero__in=casilleros, fecha__gte=start_date).values('type').annotate(count=Count('id'))

        log_counts = {tipo: 0 for tipo in TIPOS_LOGS}
        for stat in log_stats:
            log_counts[stat['type']] = stat['count']

        chart_labels = list(log_counts.keys())
        chart_data = list(log_counts.values())

        context = {
            'name': name,
            'last_name': last_name,
            'role': user.role,
            'casilleros': casilleros,
            'chart_labels': chart_labels,
            'chart_data': chart_data,
            'total_time_used': total_time_formatted,
        }

    return render(request, "base/home.html", context)


@login_required(login_url='/login')
def get_logs_statistics(request):
    user = request.user
    days = int(request.GET.get('days', 7))  # Número de días (por defecto: 7)
    start_date = now() - timedelta(days=days)

    if user.role == "Superuser":
        # Superusuario: Estadísticas generales de logs
        casillero_logs = Logs.objects.filter(fecha__gte=start_date).values('casillero__identificador').annotate(
            total_interactions=Count('id')
        )
        labels = [log['casillero__identificador'] for log in casillero_logs]
        data = [log['total_interactions'] for log in casillero_logs]
    else:
        # Usuario normal: Logs específicos de sus casilleros
        casilleros = Casillero.objects.filter(email=user.email)
        log_stats = Logs.objects.filter(casillero__in=casilleros, fecha__gte=start_date).values('type').annotate(count=Count('id'))

        TIPOS_LOGS = ["Apertura", "Cierre", "Cambio_contraseña"]
        log_counts = {tipo: 0 for tipo in TIPOS_LOGS}
        for stat in log_stats:
            log_counts[stat['type']] = stat['count']

        labels = list(log_counts.keys())
        data = list(log_counts.values())

    return JsonResponse({
        'labels': labels,
        'data': data,
    })

casillerosapp/templates/controladores/detalle_controlador.html
{% extends 'base/base.html' %}

{% load static %}
{% load custom_filters %}.

{% block title %}Detalle del Controlador{% endblock %}

{% block content %}
<div class="dashboard-container p-4">
    <div class="dashboard-header bg-dark-gray text-white rounded-top p-3 mb-4">
        <a href="{% url 'lista_controladores' %}" class="btn btn-secondary mt-4">Volver a la lista de controladores</a>
        <br>
        <br>
        <h1 class="text-center">Controlador: {{ controlador.nombre }}</h1>
        <p class="text-center">Última conexión: {{ ultima_conexion|date:"d/m/Y H:i" }}</p>
        <p class="text-center">{{ estado_conexion}}</p>
    </div>
    <div class="dashboard-body bg-white p-3 rounded-bottom">
        <h3 class="mt-3 mb-4">Casilleros Asociados</h3>
        <div class="casilleros-list overflow-auto" style="max-height: 70vh;">
            {% for casillero in casilleros %}
            <div class="casillero-card mb-3 border-top border-bottom border-left border-right border-dark-gray">
                <div class="card-body">
                    <h5 class="card-title">{{ casillero.identificador }}</h5>
                    <p class="card-text">Ubicación: {{ casillero.ubicacion }}</p>
                    <p class="card-text">Estado: {{ casillero.abierto|yesno:"Abierto,Cerrado" }}</p>
                    <p class="card-text">Dueño: {{ casillero.email|default:"Sin Dueño" }}</p>
                    <p class="card-text">Clave Asignada:
                        {% for char in casillero.clave %}
                            <img src="{% static 'assets/Logos/' %}{{ char }}.svg" alt="{{ char }}" style="width: 40px; height: 40px; display: inline-block; vertical-align: middle;">
                        {% endfor %}
                    </p>
                    <br>
                    <button class="btn" style="background-color: rgb(123, 183, 236);" data-bs-toggle="modal" data-bs-target="#modalCambiarClave{{ casillero.id }}" data-casillero-id="{{ casillero.id }}">Cambiar clave</button>
                    <button
                        class="btn"
                        style="background-color: #333; color: white;"
                        data-bs-toggle="modal"
                        data-bs-target="#modalLogs{{ casillero.id }}"
                        onclick="loadPage(1, {{ casillero.id }});">
                        Actividad Casillero
                    </button>
                    <div class="modal fade" id="modalCambiarClave{{ casillero.id }}" tabindex="-1" aria-labelledby="modalCambiarClaveLabel{{ casillero.id }}" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalCambiarClaveLabel{{ casillero.id }}">Cambiar Clave de Casillero: {{ casillero.identificador }}</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body" id="modalBody{{ casillero.id }}">
                                    <p>Cargando formulario...</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal fade" id="modalLogs{{ casillero.id }}" tabindex="-1" aria-labelledby="modalLogsLabel{{ casillero.id }}" aria-hidden="true">
                        <div class="modal-dialog modal-xl"> <!-- Usa modal-xl para un modal más grande -->
                            <div class="modal-content">
                                <div class="modal-header" style="justify-content: center; text-align: center;">
                                    <h2 class="modal-title w-100" id="modalLogsLabel{{ casillero.id }}" style="font-family: 'Montserrat', sans-serif; font-weight: bold;">
                                        Actividad del Casillero {{ casillero.identificador }}
                                    </h2>
                                    <button type="button" class="btn-close position-absolute end-0 me-3" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body" id="modalBodyLogs{{ casillero.id }}">
                                    <!-- Aquí se cargarán los logs paginados -->
                                    <p>Cargando...</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <p class="text-center">Este controlador no tiene casilleros asignados.</p>
            {% endfor %}
        </div>
    </div>
</div>

<script>
    function loadLogs(casilleroId) {
        const url = `/obtener_logs/${casilleroId}/`;
        fetch(url)
            .then(response => response.text())
            .then(html => {
                document.getElementById('logsContent').innerHTML = html;
            })
            .catch(error => console.error('Error cargando logs:', error));
    }

    function loadPage(pageNumber, casilleroId) {
        if (!casilleroId) {
            console.error("El casilleroId es inválido:", casilleroId);
            return; // Detén la ejecución si no hay casillero_id
        }

        fetch(`/obtener_logs/${casilleroId}/?page=${pageNumber}`)
            .then(response => response.text())
            .then(html => {
                // Actualiza solo el contenido del modal correspondiente
                const modalBody = document.querySelector(`#modalBodyLogs${casilleroId}`);
                if (modalBody) {
                    modalBody.innerHTML = html;
                } else {
                    console.error("No se encontró el modalBody con ID:", `#modalBodyLogs${casilleroId}`);
                }
            })
            .catch(error => console.error('Error al cargar la página:', error));
    }
</script>

<style>
    /* Estilo específico para el modal de logs */
    #modalLogs{{ casillero.id }} .modal-dialog {
        max-width: 90%;
        max-height: 90%;
    }

    #modalLogs{{ casillero.id }} .modal-content {
        height: 100%;
        display: flex;
        flex-direction: column;
    }

    #modalLogs{{ casillero.id }} .modal-body {
        flex-grow: 1;
        overflow-y: auto;
    }

    /* Estilo para los demás elementos */
    .modal-content {
        border-radius: 10px;
    }

    /* Alinear botones en la misma línea */
    .casillero-card .btn {
        margin-right: 10px;
    }

    .casillero-card {
        display: flex;
        flex-direction: column;
        gap: 10px; /* Espaciado uniforme entre elementos */
    }

    .casillero-card .card-text {
        margin-bottom: 5px; /* Reduce espacio innecesario */
    }

    .btn-warning,
    .btn-info {
        padding: 10px 20px; /* Botones más amplios y uniformes */
    }

    .modal-open .casillero-card:hover {
        transform: none;
        box-shadow: none;
    }

    .modal-body input {
        width: 20%; /* Hacemos que los campos se alineen bien */
    }

    .dashboard-container {
        border: 2px solid #333; /* Borde del dashboard */
        border-radius: 15px;
        background-color: #222; /* Fondo del dashboard */
        color: #ffffffe3;
        margin: 20px auto;
        max-width: 90%; /* Ajustar tamaño del dashboard */
        padding: 0;
    }

    .dashboard-header {
        background-color: #333; /* Fondo gris oscuro */
        color: #ffffff;
        border-top-left-radius: 15px;
        border-top-right-radius: 15px;
    }

    .dashboard-body {
        border-bottom-left-radius: 15px;
        border-bottom-right-radius: 15px;
    }

    .casillero-card {
        background-color: #ffffffe5; /* Fondo blanco */
        color: #000; /* Letra negra */
        padding: 15px;
        border-radius: 8px;
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }

    .casillero-card:hover {
        transform: scale(1.03);
        box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.3);
    }

    .text-center {
        font-family: 'Montserrat', sans-serif;
        font-weight: bold;
    }

    .btn {
        font-family: 'Montserrat', sans-serif;
        font-weight: bold;
    }
    
    body {
        font-family: 'Montserrat', sans-serif;
        background: url("{% static 'assets/Logos/fondo_login1.jpeg' %}") no-repeat center center fixed;
        background-size: cover;
    }
</style>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        var botonesModal = document.querySelectorAll('[data-bs-toggle="modal"]');

        botonesModal.forEach(function (boton) {
            boton.addEventListener('click', function (event) {
                var casilleroId = event.target.getAttribute('data-casillero-id');
                var modalBody = document.getElementById('modalBody' + casilleroId);

                fetch("{% url 'cargar_formulario_usuario' 0 %}".replace("0", casilleroId))
                    .then(response => response.text())
                    .then(html => {
                        modalBody.innerHTML = html;

                        // Agregar script para cambiar la apariencia del select con la imagen
                        const imagenesOpciones = {
                            'A': "{% static 'assets/Logos/A.svg' %}",
                            'B': "{% static 'assets/Logos/B.svg' %}",
                            'C': "{% static 'assets/Logos/C.svg' %}",
                            'D': "{% static 'assets/Logos/D.svg' %}",
                            'E': "{% static 'assets/Logos/E.svg' %}",
                            'F': "{% static 'assets/Logos/F.svg' %}"
                        };

                        document.querySelectorAll('.form-select').forEach(select => {
                            select.addEventListener('change', function () {
                                const selectedOption = select.options[select.selectedIndex].value;
                                const imagen = imagenesOpciones[selectedOption];
                                if (imagen) {
                                    select.style.background = `url(${imagen}) no-repeat center center / 40px 40px`;
                                    select.style.color = 'transparent'; // Oculta el texto
                                    select.style.height = '50px'; // Aumenta el alto del select
                                }
                            });

                            // Inicializar la imagen si ya hay una opción seleccionada
                            const initialOption = select.options[select.selectedIndex].value;
                            const initialImage = imagenesOpciones[initialOption];
                            if (initialImage) {
                                select.style.background = `url(${initialImage}) no-repeat center center / 40px 40px`;
                                select.style.color = 'transparent'; // Oculta el texto
                                select.style.height = '50px'; // Aumenta el alto del select
                            }
                        });

                    })
                    .catch(error => {
                        modalBody.innerHTML = '<p>Error al cargar el formulario.</p>';
                        console.error('Error al cargar formulario:', error);
                    });
            });
        });
    });
</script>
<script>
    function closeAccordion(logId) {
        const accordionRow = document.getElementById(`accordionLog${logId}`);
        if (accordionRow) {
            accordionRow.classList.remove('show'); // Elimina la clase 'show' para cerrar el acordeón
        }
    }

    function loadPage(pageNumber, casilleroId) {
        if (!casilleroId) {
            console.error("El casilleroId es inválido:", casilleroId);
            return; // Detén la ejecución si no hay casillero_id
        }

        fetch(`/obtener_logs/${casilleroId}/?page=${pageNumber}`)
            .then(response => response.text())
            .then(html => {
                // Actualiza solo el contenido del modal correspondiente
                const modalBody = document.querySelector(`#modalBodyLogs${casilleroId}`);
                if (modalBody) {
                    modalBody.innerHTML = html;
                } else {
                    console.error("No se encontró el modalBody con ID:", `#modalBodyLogs${casilleroId}`);
                }
            })
            .catch(error => console.error('Error al cargar la página:', error));
    }
</script>


{% endblock %}

casillerosapp/templates/controladores/lista_controladores.html
{% extends 'base/base.html' %}

{% block title %}Lista de Controladores{% endblock %}
{% load custom_filters %}
{% load static %}

{% block content %}
<div class="dashboard-container mx-auto mt-4 mb-4" style="display: flex; flex-direction: column; height: 85vh; border-radius: 15px; overflow: hidden; border: 2px solid #343a40; max-width: 1200px;">
    <!-- Header del dashboard -->
    <div class="dashboard-header p-3" style="background-color: #343a40; text-align: center;">
        <h1 class="mb-0 text-white fw-bold" style="font-family: 'Montserrat', sans-serif;">Controladores</h1>
    </div>

    <!-- Contenido del dashboard -->
    <div class="dashboard-content flex-grow-1" style="overflow-y: auto; background-color: #f8f9faf0; padding: 20px; font-family: 'Montserrat', sans-serif;">
        {% for controlador in controladores %}
        <div class="controlador-card shadow-sm p-3 mb-4" style="background-color: #ffffffeb; border-top: 3px solid #343a40; border-bottom: 3px solid #343a40; border-left: 3px solid #343a40; border-right: 3px solid #343a40; border-radius: 10px; transition: transform 0.3s ease, box-shadow 0.3s ease;">
            <a href="{% url 'detalle_controlador' controlador.id %}" style="text-decoration: none; color: inherit;">
                <h5 class="card-title" style="color: #000; font-family: 'Montserrat', sans-serif;">{{ controlador.nombre }}</h5>
                <p class="card-text" style="color: #000; font-family: 'Montserrat', sans-serif;">
                    Última conexión: {{ controlador.ultima_conexion|restar_horas:3|date:"d/m/Y H:i" }}
                </p>
            </a>
        </div>
        {% endfor %}
    </div>

    <!-- Footer del dashboard -->
    <div class="dashboard-footer p-2" style="background-color: #343a40; text-align: center;">
        <!-- Espacio vacío para el footer -->
    </div>
</div>

<style>
    /* Sombra y animación al pasar el mouse sobre la tarjeta del controlador */
    .controlador-card:hover {
        transform: scale(1.05);
        box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.3);
    }

    /* Asegura que toda la tipografía esté en la fuente Montserrat */
    body, .card-title, .card-text, h1, p, a {
        font-family: 'Montserrat', sans-serif;
    }

    body {
        background: url("{% static 'assets/Logos/fondo_login1.jpeg' %}") no-repeat center center fixed;
        background-size: cover;
    }
</style>
{% endblock %}

casillerosapp/templates/controladores/modal_formulario_usuario.html
{% load static %}

<form method="post" action="{% url 'actualizar_casillero_usuario' casillero.id %}">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_usuario_email" class="form-label">{{ form_usuario.usuario_email.label }}</label>
        {{ form_usuario.usuario_email }}
        {% if form_usuario.usuario_email.errors %}
            <div class="text-danger">
                {% for error in form_usuario.usuario_email.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
    </div>

    <p>Por favor selecciona los nuevos caracteres de la clave (4 caracteres).</p>
    <div class="d-flex justify-content-center gap-2 mb-3">
        <!-- Renderizar los selectores de clave con estilo de Bootstrap -->
        <div class="form-group">
            {{ form_usuario.clave1 }}
        </div>
        <div class="form-group">
            {{ form_usuario.clave2 }}
        </div>
        <div class="form-group">
            {{ form_usuario.clave3 }}
        </div>
        <div class="form-group">
            {{ form_usuario.clave4 }}
        </div>
    </div>

    <div class="text-center mt-3">
        <button type="submit" class="btn btn-primary">Confirmar</button>
    </div>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        console.log('Script cargado y ejecutándose'); // Verifica que el script se cargue

        const imagenesOpciones = {
            'A': "{% static 'assets/Logos/A.svg' %}",
            'B': "{% static 'assets/Logos/B.svg' %}",
            'C': "{% static 'assets/Logos/C.svg' %}",
            'D': "{% static 'assets/Logos/D.svg' %}",
            'E': "{% static 'assets/Logos/E.svg' %}",
            'F': "{% static 'assets/Logos/F.svg' %}"
        };

        document.querySelectorAll('.form-select').forEach(select => {
            console.log('Select encontrado:', select);

            select.addEventListener('change', function() {
                const selectedOption = select.options[select.selectedIndex].value;
                const imagen = imagenesOpciones[selectedOption];
                console.log('Opción seleccionada:', selectedOption, 'Imagen:', imagen);
                if (imagen) {
                    select.style.background = `url(${imagen}) no-repeat right center / 20px 20px`;
                }
            });

            const initialOption = select.options[select.selectedIndex].value;
            const initialImage = imagenesOpciones[initialOption];
            if (initialImage) {
                select.style.background = `url(${initialImage}) no-repeat right center / 20px 20px`;
            }
        });
    });
</script>